removed normal proj references due to change in capabilities.xml
icesat2py/icepyx pull request #153
Opened 2020-11-25 19:38 UTC by asteiker

After fixing local fork issues, this should now show only the changes I made to is2ref.py. CMR is down due to a major AWS outage so once again I couldn't test this but like i said in my other PR, these changes have already been implemented in one of our NSIDC notebooks so this should resolve the problem due to the capabilities.xml updates in our last API release.

2020-11-30 19:34 UTC, JessicaS11 requested changes
Hey @asteiker! This looks great and I was able to run an example notebook with no issues. Would you be able to run `pip install pre-commit` on your local system, then re-commit the file to your fix-proj fork (then it should automatically add the updates to this PR)? If git complains about no files changed, you may need to make a minor modification to the file to get it to detect the changes. What I'm trying to have happen is the pre-commit trigger for running black, which is a code formatter. The first time you try to commit, it should say that black failed and then reformat the file. You'll have to then run the commit a second time, and it should all work.
<img width="788" alt="image" src="https://user-images.githubusercontent.com/11756442/100655282-0f5ec480-3319-11eb-8bf9-4cc445ceeab7.png">
This will help keep the code-base consistently formatted so we don't have lines (e.g. 93(orig)/84(updated) - I'll point them out in-line) that show up as changes even though the change was from ' to " around a string, etc. I can't push the changes to your PR since it's on your personal branch.

2020-11-30 19:36 UTC, JessicaS11 commented on icepyx/core/is2ref.py
> +    projections = [Projection.attrib for Projection in root.iter('Projection')]
formatting inconsistencies that are fixed by black during the pre-commit run to make it clearer where code has been changed in the diff view (i.e. what we're looking at)

2020-12-01 04:50 UTC, asteiker commented
@JessicaS11 Sorry for this issue! When I ran `pip install pre-commit` locally it says that it is already installed, which is strange. I ended up just changes those quotes back to manually fix the problem. I hope this somewhat solves the issue. Not sure if you have any other thoughts for why that trigger didnt happen even though I seem to have `pre-commit` already installed?

2020-12-01 15:51 UTC, JessicaS11 approved these changes

2020-12-01 15:51 UTC, merged